name: Publish Newspaper

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:

      - name: Get repository
        uses: actions/checkout@v4

      - name: Generate website
        run: python generator.py

      - name: Commit generated website
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add index.html

          git diff --cached --quiet || \
            git commit -m "Update newspaper website"

          git push
